tienda/apps/sucursal/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.sucursal.views import sucursal_view, sucursal_list, sucursal_edit, sucursal_delete

urlpatterns = [
    
    url(r'^nuevo$', login_required(sucursal_view), name='sucursal_crear'),
    url(r'^listar$', login_required(sucursal_list), name='sucursal_listar'),
    url(r'^editar/(?P<id_sucursal>\d+)/$', login_required(sucursal_edit), name='sucursal_editar'),
    url(r'^eliminar/(?P<id_sucursal>\d+)/$', login_required(sucursal_delete), name='sucursal_eliminar'),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, logout_then_login
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^index/', include (('apps.producto.urls', 'producto'),namespace = "producto")),
    url(r'^sucursal/', include (('apps.sucursal.urls', 'sucursal'),namespace = "sucursal")),
    url(r'^user/', include ('apps.usuario.urls')),
    url(r'^accounts/login/', LoginView.as_view(), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

tienda/apps/sucursal/models.py
from django.db import models

# Create your models here.
# modelo de comuna
class Comuna (models.Model):
    nombreComuna = models.CharField(max_length = 50)

    # para que retorne el nombre de la comuna
    def __str__(self):
        return '{}'.format(self.nombreComuna)

class Ciudad (models.Model):
    nombreCiudad = models.CharField(max_length = 50)
  


    # para que retorne el nombre de la ciudad
    def __str__(self):
        return '{}'.format(self.nombreCiudad)


class Sucursal (models.Model):
    nombreTienda = models.CharField(max_length = 50) 
    direccion = models.CharField(max_length = 150) 
    telefono = models.CharField(max_length = 10) 
    correo = models.CharField(max_length = 50) 
    encargado = models.CharField(max_length = 50) 
    comuna = models.ForeignKey(Comuna, default=1, on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, default=1, on_delete=models.CASCADE)


    # para que retorne el nombre de la comuna y no el ID
    def __str__(self):
        return '{}'.format(self.nombreTienda)

tienda/apps/sucursal/forms.py
from django import forms
from apps.sucursal.models import Sucursal

class SucursalForm(forms.ModelForm):
    
    class Meta:
        model = Sucursal

        fields = [
            'nombreTienda',
            'direccion',
            'telefono',
            'correo',
            'encargado',
            'comuna' ,
            'ciudad' ,
            
        ]

        label = {
            'nombreTienda' : 'Nombre de tienda',
            'direccion' : 'Dirección',
            'telefono' : 'Teléfono',
            'correo' : 'Correo Electrónico',
            'encargado' : 'Encargado de Local',
            'comuna' : 'Comuna',
            'ciudad' : 'Ciudad',
            
        }

        widgets = {

            'nombreTienda' : forms.TextInput(attrs={'class':'form-control'}),
            'direccion' : forms.TextInput(attrs={'class':'form-control'}),
            'telefono' : forms.TextInput(attrs={'class':'form-control'}),
            'correo' : forms.TextInput(attrs={'class':'form-control'}),
            'encargado' :forms.TextInput(attrs={'class':'form-control'}),
            'comuna' : forms.Select(attrs={'class':'select'}),
            'ciudad' : forms.Select(attrs={'class':'select'}),
            
           
        }

tienda/apps/sucursal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound
from django.views.generic import CreateView
from django.urls import reverse_lazy
from apps.sucursal.forms import SucursalForm
from apps.sucursal.models import Sucursal
from django.contrib.auth.decorators import login_required


# Create your views here.


# para poder crear una nueva sucursal
def sucursal_view(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = SucursalForm(request.POST)
            
            if form.is_valid():
                form.save()
            return redirect('sucursal:sucursal_listar')
        else:
            form = SucursalForm()
        return render(request, 'sucursal/sucursal_form.html', {'form':form})
    else:
        return HttpResponseNotFound('<h1>Página no encontrada o no tienes los suficientes permisos para entrar a ella :(</h1>')


# para listar todos las sucursales existentes
def sucursal_list(request):
    sucursal = Sucursal.objects.all()
    contexto = {'sucursales':sucursal}
    return render(request, 'sucursal\sucursal_list.html', contexto)

#  para poder editar una sucursal mandando su id
def sucursal_edit(request, id_sucursal):

    if request.user.is_superuser:
        sucursal = Sucursal.objects.get(id=id_sucursal)
        if request.method == 'GET':
            form = SucursalForm(instance=sucursal)
        else:
            form = SucursalForm(request.POST, instance=sucursal)
            if form.is_valid():
                form.save()
            return redirect('sucursal:sucursal_listar')
        return render(request,'sucursal/sucursal_form.html', {'form':form})
    else:
        return HttpResponseNotFound('<h1>Página no encontrada o no tienes los suficientes permisos para entrar a ella :(</h1>')


# para poder eliminar una sucursal mandando su id
def sucursal_delete(request, id_sucursal):
    if request.user.is_superuser:    
        sucursal = Sucursal.objects.get(id=id_sucursal)
        if request.method == 'POST':
            sucursal.delete()
            return redirect('sucursal:sucursal_listar')
        return render(request,'sucursal/sucursal_delete.html', {'sucursal':sucursal})
    else:
        return HttpResponseNotFound('<h1>Página no encontrada o no tienes los suficientes permisos para entrar a ella :(</h1>')

tienda/templates/sucursal/sucursal_delete.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load materializecss %}

{% block title %} ELIMINAR SUCURSAL {% endblock %}

{% block content %}
<div class="container">
    <div class="row center">
        <form method="post">
            {% csrf_token %}
            <h3>¿Desea eliminar el registro de {{ sucursal.nombre }}?</h3>

            <button class="btn waves-effect waves-light red" type="submit">Sí, eliminar</button>
            <a class="btn waves-effect waves-light blue" href="{% url 'sucursal:sucursal_listar' %}">Cancelar</a>
        </form>

    </div>
   <br><br><br>
  </div>

{% endblock %}

tienda/templates/sucursal/sucursal_form.html
<!--Para heredar de la plantilla base el diseño de la pag-->
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load materializecss %}

{% block title %} CREAR SUCURSAL{% endblock %}

<!--Para cambiar el contenido que se encuentra en esta pag-->
{% block content %}
<div class="container">

    <form method="post">
        {% csrf_token %}

        <div class="row center">
            <h1>Agregar nueva sucursal</h1>
        </div>
        

        {{ form.nombreTienda|materializecss:'s6' }}
        {{ form.direccion|materializecss:'s6' }}
        {{ form.telefono|materializecss:'s6' }}
        {{ form.correo|materializecss:'s6' }}
        {{ form.encargado|materializecss:'s6' }}
        {{ form.comuna|materializecss:'s6' }}
        {{ form.ciudad|materializecss:'s6' }}

        <div class="row center">
            <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                <i class="material-icons right">done</i>
            </button>

            <a class="btn waves-effect waves-light red" href="{% url 'sucursal:sucursal_listar' %}">Cancelar
                <i class="material-icons right">keyboard_backspace</i>
            </a>

        </div>

        

    </form>
</div>

{% endblock %}

tienda/templates/sucursal/sucursal_list.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% load materializecss %}

{% block title %} LISTA DE SUCURSALES {% endblock %}

{% block content %}

<div class="container">
    <br>
    <div class="row center">
        <h1>Lista de Sucursales</h1>
    </div>
    {% if request.user.is_superuser %}
    <div class="row right">
        <a class="btn waves-effect waves-light " href="{% url 'sucursal:sucursal_crear' %}">Nuevo
            <i class="material-icons right">add</i>
        </a>
    </div>
    {% endif %}
    <br><br><br>

    <div class="row ">

        <div class="">


            <table class="table table-bordered">
                <thead>
                    <tr>

                        <td>Nombre</td>
                        <td>Dirección</td>
                        <td style="width: 250px;">Teléfono</td>
                        <td>Correo</td>
                        <td>Encarcado</td>
                        <td>Comuna</td>
                        <td>Ciudad</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    {% if sucursales %}
                    {% for sucursal in sucursales %}
                    <tr>

                        <td>{{ sucursal.nombreTienda }}</td>
                        <td>{{ sucursal.direccion }}</td>
                        <td>{{ sucursal.telefono }}</td>
                        <td>{{ sucursal.correo }}</td>
                        <td>{{ sucursal.encargado }}</td>
                        <td>{{ sucursal.comuna }}</td>
                        <td>{{ sucursal.ciudad }}</td>
                        <td>
                            <a class="btn waves-effect waves-light orange" href="{% url 'sucursal:sucursal_editar' sucursal.id %}">Editar</a>
                            <a class="btn waves-effect waves-light red" href="{% url 'sucursal:sucursal_eliminar' sucursal.id %}">Eliminar</a>


                        </td>
                    </tr>
                    {% endfor %}

                    {% else %}
                    <h1>No hay registros de sucursales</h1>

                    {% endif %}

                </tbody>
            </table>


        </div>


    </div>


</div>

{% endblock %}