tienda/apps/producto/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.producto.views import index, producto_view, producto_list, producto_edit, producto_delete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(producto_view), name='producto_crear'),
    url(r'^listar$', login_required(producto_list), name='producto_listar'),
    url(r'^editar/(?P<id_producto>\d+)/$', login_required(producto_edit), name='producto_editar'),
    url(r'^eliminar/(?P<id_producto>\d+)/$', login_required(producto_delete), name='producto_eliminar'),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, logout_then_login
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^index/', include (('apps.producto.urls', 'producto'),namespace = "producto")),
    url(r'^sucursal/', include (('apps.sucursal.urls', 'sucursal'),namespace = "sucursal")),
    url(r'^user/', include ('apps.usuario.urls')),
    url(r'^accounts/login/', LoginView.as_view(), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

tienda/apps/producto/models.py
from django.db import models

# Create your models here.


# Modelo de tipo de producto
class TipoProducto(models.Model):
    nombreTipo = models.CharField(max_length = 50)

    # para que se muestre el nombre del tipo de producto y no su código
    # al momento de ingresar un nuevo producto

    def __str__(self):
        return '{}'.format(self.nombreTipo)


# Modelo para el producto

class Producto (models.Model):
    nombre = models.CharField(max_length = 50)
    descripcion =models.CharField(max_length = 150)
    precio = models.CharField(max_length = 50)
    tipo = models.ForeignKey(TipoProducto, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.nombre)

tienda/apps/producto/forms.py
from django import forms
from apps.producto.models import Producto

class ProductoForm(forms.ModelForm):
    
    class Meta:
        model = Producto

        fields = [
            'nombre',
            'tipo',
            'descripcion',
            'precio',
            
        ]

        label = {
            'nombre' : 'Nombre',
            'tipo' : 'Tipo',
            'descripcion' : 'Descripción',
            'precio' : 'Precio',
            
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'tipo': forms.Select(attrs={'class':'select'}),
            'descripcion': forms.TextInput(attrs={'class':'input-field'}),
            'precio': forms.TextInput(attrs={'class':'input-field'}),
           
        }

tienda/apps/producto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound
from django.views.generic import CreateView
from django.urls import reverse_lazy
from apps.producto.forms import ProductoForm
from apps.producto.models import Producto
from django.contrib.auth.decorators import login_required

# Create your views here.


# view para el index de la página
def index(request):
    return render (request, 'principal/index.html')


# para poder crear un nuevo producto
def producto_view(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = ProductoForm(request.POST)
            
            if form.is_valid():
                form.save()
            return redirect('producto:producto_listar')
        else:
            form = ProductoForm()
        return render(request, 'producto/producto_form.html', {'form':form})
    else:
        return HttpResponseNotFound('<h1>Página no encontrada o no tienes los suficientes permisos para entrar a ella :(</h1>')


# para listar todos los productos existentes
def producto_list(request):
    producto = Producto.objects.all()
    contexto = {'productos':producto}
    return render(request, 'producto/producto_list.html', contexto)

#  para poder editar un producto mandando su id
def producto_edit(request, id_producto):

    if request.user.is_superuser:
        producto = Producto.objects.get(id=id_producto)
        if request.method == 'GET':
            form = ProductoForm(instance=producto)
        else:
            form = ProductoForm(request.POST, instance=producto)
            if form.is_valid():
                form.save()
            return redirect('producto:producto_listar')
        return render(request,'producto/producto_form.html',{'form':form})
    else:
        return HttpResponseNotFound('<h1>Página no encontrada o no tienes los suficientes permisos para entrar a ella :(</h1>')


# para poder eliminar un producto mandando su id
def producto_delete(request, id_producto):
    if request.user.is_superuser:    
        producto = Producto.objects.get(id=id_producto)
        if request.method == 'POST':
            producto.delete()
            return redirect('producto:producto_listar')
        return render(request,'producto/producto_delete.html', {'producto':producto})
    else:
        return HttpResponseNotFound('<h1>Página no encontrada o no tienes los suficientes permisos para entrar a ella :(</h1>')

tienda/templates/producto/producto_delete.html
{% extends 'base/base.html' %}
{% load materializecss %}
{% load staticfiles %}

{% block title %} Eliminar {{producto.nombre}} {% endblock %}

{% block content %}
  
  <div class="container">
    <div class="row center">
        <form method="post">
            {% csrf_token %}
            <h3>¿Desea eliminar el registro de {{ producto.nombre }}?</h3>

            <button class="btn waves-effect waves-light red" type="submit">Sí, eliminar</button>
            <a class="btn waves-effect waves-light blue" href="{% url 'producto:producto_listar' %}">Cancelar</a>
        </form>

    </div>
   <br><br><br>
  </div>

 {% endblock %}

tienda/templates/producto/producto_form.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% load materializecss %}

{% block title %} Nuevo Producto {% endblock %}

{% block content%}
<div class="container">

  <div class="center">
    <h3> Crear producto</h3>
  </div>

  <form method="post">
    {% csrf_token %}
    <div class="row ">

      <div class="col s12">
        <div class="col s6">

          <label for="nombre">Nombre</label>
          {{ form.nombre }}
        </div>
        <div class="col s6">
          <label for="tipo">Tipo</label>
          {{ form.tipo }}
        </div>


      </div>



    </div>

    <div class="row">
      <div class="col s12">
        <label for="descripcion">Descripción</label>
        {{ form.descripcion }}
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div class="col s4">
          <label for="precio">Precio</label>
          {{ form.precio}}
        </div>

        
      </div>
    </div>
    <br>
    <div class="row center">

      <button class="btn waves-effect waves-light center" type="submit" name="action">Guardar</button>

    </div>
  </form>
</div>

{% endblock %}

tienda/templates/producto/producto_list.html
{% extends 'base/base.html' %}

{% load staticfiles %}

{% load materializecss %}

{% block title %}Lista de productos{% endblock %}

{% block content %}
<div class="container">

  <div class="row center"><h2>Lista de productos</h2></div>

  <div class="row right"><a class="btn waves-effect waves-light" href="{% url 'producto:producto_crear' %}">Nuevo
    <i class="material-icons right">add</i>
  </a></div>
  <table class="table table-bordered">
    <thead>
      <tr>

        <td>Nombre</td>
        <td>Tipo</td>
        <td>Descripción</td>
        <td>Precio</td>
        <td>Acciones</td>
      </tr>
    </thead>
    <tbody>
      {% if productos %}
      {% for producto in productos %}
      <tr>

        <td>{{ producto.nombre }}</td>
        <td>{{ producto.tipo }}</td>
        <td>{{ producto.descripcion }}</td>
        <td>$ {{ producto.precio }}</td>
        
        <td>
          <a class="btn waves-effect waves-light orange" href="{% url 'producto:producto_editar' producto.id %}">Editar</a>
          <a class="btn waves-effect waves-light red" href="{% url 'producto:producto_eliminar' producto.id %}">Eliminar</a>


        </td>
      </tr>

      {% endfor %}

      {% else %}

      <h1>No existen registros</h1>

      {% endif %}
    </tbody>
  </table>

</div>

{% endblock %}