tienda/apps/producto/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.producto.views import index, producto_view, producto_list, producto_edit, producto_delete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required(producto_view), name='producto_crear'),
    url(r'^listar$', login_required(producto_list), name='producto_listar'),
    url(r'^editar/(?P<id_producto>\d+)/$', login_required(producto_edit), name='producto_editar'),
    url(r'^eliminar/(?P<id_producto>\d+)/$', login_required(producto_delete), name='producto_eliminar'),
]

tienda/apps/sucursal/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.sucursal.views import sucursal_view, sucursal_list, sucursal_edit, sucursal_delete

urlpatterns = [
    
    url(r'^nuevo$', login_required(sucursal_view), name='sucursal_crear'),
    url(r'^listar$', login_required(sucursal_list), name='sucursal_listar'),
    url(r'^editar/(?P<id_sucursal>\d+)/$', login_required(sucursal_edit), name='sucursal_editar'),
    url(r'^eliminar/(?P<id_sucursal>\d+)/$', login_required(sucursal_delete), name='sucursal_eliminar'),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LoginView, logout_then_login
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^index/', include (('apps.producto.urls', 'producto'),namespace = "producto")),
    url(r'^sucursal/', include (('apps.sucursal.urls', 'sucursal'),namespace = "sucursal")),
    url(r'^user/', include ('apps.usuario.urls')),
    url(r'^accounts/login/', LoginView.as_view(), name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
]

tienda/templates/base/base.html
{% load materializecss %}
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{% block title %} ElectroTech {% endblock %} </title>

  {% block css %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
{% endblock css %}
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %} " type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  <nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="{% url 'producto:index' %}" class="brand-logo">ElectroTech</a>
      <ul class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
          <li><a href="">Bienvenido {{request.user.username}}</a>  </li>
          {% endif %}
        {% if user.is_authenticated == False %} 
        <li><a href="{% url 'login' %}">Iniciar sesión</a></li>
        {% endif %}
        {% if user.is_authenticated %} 
        <li><a href="{% url 'producto:producto_listar' %}">Productos</a></li>
        <li><a href="{% url 'sucursal:sucursal_listar' %}">Sucursales</a></li>
        <li><a href="#">Ventas</a></li>
        <li><a href="{% url 'registrar' %}">Usuarios</a></li>
        <li><a href="{% url 'logout' %}">Salir</a></li>
        {% endif %}
      </ul>

      <ul id="nav-mobile" class="sidenav">
        {% if user.is_authenticated == False %}
        <li><a href="{% url 'login' %}">Iniciar sesión</a></li>
        {% endif %}
        {% if user.is_authenticated %} 
        <li><a href="#">Productos</a></li>
        <li><a href="#">Sucursales</a></li>
        <li><a href="#">Ventas</a></li>
        <li><a href="{% url 'registrar' %}">Usuarios</a></li>
        <li><a href="#">Salir</a></li>
        {% endif %}
        
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
   {% block content %}{% endblock %}
  
  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Información de contacto</h5>
          <p class="grey-text text-lighten-4">Mantengámonos conectados!</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Contacto</h5>
          <ul>
            <li><a class="white-text" href="#!">Facebook</a></li>
            <li><a class="white-text" href="#!">Twitter</a></li>
            <li><a class="white-text" href="#!">Instagram</a></li>
            <li><a class="white-text" href="#!">+5695253597</a></li>
            <li><a class="white-text" href="#!">info@ElectroTech.cl</a></li>
          </ul>
        </div>
        
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Derechos reservados <a class="brown-text text-lighten-3" href="">ElectroTech</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>

  
{% block javascript %}
<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

// Initialize materialize data picker
$('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
$('select').formSelect();

});

</script>

{% endblock javascript %}
  </body>
</html>